version: '3.3'


services:
  bot:
    container_name: ulul_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/services/ggeek_bot
    env_file:
      - .env